### ISSUE TITLE
Cannot launch Gazebo world 

### ISSUE THREAD

**Issue by khairiyah98** [AcutronicRobotics/ros2learn#9]
Hi,

I executed these commands:
```bash
cd ~/ros2learn/experiments/examples/MARA
python3 train_ppo2_mlp.py -g
```
However, I encounter this error and I am unable to launch the robotic arm in Gazebo. The error is as follows:

![image](https://user-images.githubusercontent.com/42514538/59994828-d92f0700-9687-11e9-8f00-00c83d72eb98.png)

Does anyone know how to fix this issue? Your help would be greatly appreciated.

**Comment by nzlz** [comment]
Which branch instructions did you follow? master/dashing/crystal..

Which gazebo version do you have? gazebo -v

Also, could you provide a more extended error trace?

**Comment by khairiyah98** [comment]
I followed the master branch's instructions.

My gazebo version is 9.0.0.

Here is a more extended error trace:
![image](https://user-images.githubusercontent.com/42514538/59999869-93793b00-9695-11e9-8301-b02acee69a2b.png)
![image](https://user-images.githubusercontent.com/42514538/59999891-a3911a80-9695-11e9-94a0-57f48e42c174.png)

**Comment by nzlz** [comment]
You need gazebo 9.9.0 . The easiest way would be to get rid of `ros-dashing-gazebo*` and install gazebo via one liner installation: `curl -sSL http://get.gazebosim.org | sh`.

Once you have the latest version, make sure you follow gym-gazebo2 installation instructions from the `master` branch. https://github.com/AcutronicRobotics/gym-gazebo2/blob/master/INSTALL.md. 

In case you install gazebo 9.9.0 and still get the reset_simulation service not available ...
In the [create workspace](https://github.com/AcutronicRobotics/gym-gazebo2/blob/master/INSTALL.md#create-a-ros-workspace) step, you will see that you must obtain the packages in _additional-repos.repos_ file, and that is were `gazebo_ros_pkgs` gets from in the master installation (ROS2 Dashing). 

---

@YueErro @rkojcev I believe we should update the instructions in master/dashing branches to get gazebo via the one liner instruction, same as we do in the dockerfiles (ci and dev). Are you okay with this?

**Comment by alesolano** [comment]
Just pasting the error here so everybody can arrive to this issue easily by searching it.
```
gzclient: /build/ogre-1.9-B6QkmW/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreNode.cpp:630: virtual void Ogre::Node::setScale(const Ogre::Vector3&): Assertion `!inScale.isNaN() && "Invalid vector supplied as parameter"' failed.
```

This error is because Gazebo 9.0.0 does not allow you to use dummy links with radius = 0.0, and we use those dummy links in MARA. Here is the explanation on how to hack this: https://github.com/AcutronicRobotics/gym-gazebo2/issues/31#issuecomment-501660211

I agree @nzlz we should add gazebo 9.9.0 one-liner installation to the instructions.

**Comment by khairiyah98** [comment]
Installing gazebo 9.9.0 worked! Thank you :)
